import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import HeaderBar from './Components/headerBar/HeaderBar';
import MenuBar from './Components/menu/Menu';
import FooterBar from './Components/footer/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div>
            <HeaderBar></HeaderBar>
          </div>
          <div className='container-fluid d-flex'>
            <div className='col-sm-2'>
              <MenuBar></MenuBar>
            </div>
            <div className='col'>
              {children}
            </div>
          </div>
          <FooterBar></FooterBar>
        </div>
      </body>
    </html>
  )
}
